### ISSUE TITLE
There is a problem here

### ISSUE THREAD

**Issue by ytdaxin** [ijlik/TRC20-Wallet#1]
app/Console/Commands/ScanTRC20Token.php

&order_by=block_timestamp,asc
modify
&order_by=block_timestamp,desc

**Comment by ijlik** [comment]
Please show me what kind of problem there. It refers to the official documentation of Tron here https://developers.tron.network/reference#events-by-contract-address

**Comment by ytdaxin** [comment]
ASC positive sequence only gets the old data. You can look at the timestamp. Desc is the latest correct data

**Comment by ijlik** [comment]
Of course you're right. I mistaken that things. Thank you
